{
 "title": "S3 Buckets",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster" }
  ]
 },
 "panels": [
  { "title": "Errors", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 }, "content": "\n\n" },
  { "title": "Latency", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 }, "content": "\n\n" },
  {
   "title": "Top 5 4XX Error Rate",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc(topk(5,aws_s3_4xx_errors_average))",
     "legendFormat": "{{dimension_BucketName}}"
    }
   ]
  },
  {
   "title": "Top 5 5XX Error Rate",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc(topk(5,aws_s3_5xx_errors_average))",
     "legendFormat": "{{dimension_BucketName}}"
    }
   ]
  },
  {
   "title": "Top First Byte Latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "topk(5,aws_s3_first_byte_latency_p95)",
     "legendFormat": "{{dimension_BucketName}}"
    }
   ]
  },
  {
   "title": "Top Total Request Latency ",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "topk(5,aws_s3_total_request_latency_p95)",
     "legendFormat": "{{dimension_BucketName}}"
    }
   ]
  },
  {
   "title": "4XX Error rate (Top 10)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(10,aws_s3_4xx_errors_average)",
     "legendFormat": "{{dimension_BucketName}}"
    }
   ]
  },
  {
   "title": "Top 5 First Byte Latency ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk(5,aws_s3_first_byte_latency_p95)",
     "legendFormat": "{{dimension_BucketName}}"
    }
   ]
  },
  {
   "title": "5XX Error rate (Top 10)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(10,aws_s3_5xx_errors_average)",
     "legendFormat": "{{dimension_BucketName}}"
    }
   ]
  },
  {
   "title": "Top 5 Request Latency ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk(5,aws_s3_total_request_latency_p95)",
     "legendFormat": "{{dimension_BucketName}}"
    }
   ]
  },
  { "title": "Throughput", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 19 }, "content": "\n\n" },
  { "title": "Usage", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 19 }, "content": "\n\n" },
  {
   "title": "Bitrate Up/Down",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(aws_s3_bytes_uploaded_sum) / 300",
     "legendFormat": "Upload"
    },
    {
     "expr": "avg(aws_s3_bytes_downloaded_sum) / 300",
     "legendFormat": "Download"
    }
   ]
  },
  {
   "title": "Number of Buckets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "count(aws_s3_bucket_size_bytes_average)"
    }
   ]
  },
  {
   "title": "Max Bucket",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "max(aws_s3_bucket_size_bytes_average)",
     "legendFormat": "{{dimension_BucketName}}"
    }
   ]
  },
  {
   "title": "Average Bucket",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 20 },
   "targets": [
    {
     "expr": "avg(aws_s3_bucket_size_bytes_average)"
    }
   ]
  },
  {
   "title": "Total Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum(aws_s3_bucket_size_bytes_average)"
    }
   ]
  },
  {
   "title": "Min Bucket",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 23 },
   "targets": [
    {
     "expr": "min(aws_s3_bucket_size_bytes_average)"
    }
   ]
  },
  {
   "title": "P95 Bucket",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 23 },
   "targets": [
    {
     "expr": "quantile(0.95,aws_s3_bucket_size_bytes_average)"
    }
   ]
  },
  {
   "title": "Top 5 Upstream Traffic",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sort_desc(topk(5,aws_s3_bytes_uploaded_sum))",
     "legendFormat": "{{dimension_BucketName}}"
    }
   ]
  },
  {
   "title": "Top 5 Downstream Traffic",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 26 },
   "targets": [
    {
     "expr": "sort_desc(topk(5,aws_s3_bytes_downloaded_sum))",
     "legendFormat": "{{dimension_BucketName}}"
    }
   ]
  },
  {
   "title": "Top 5 Buckets",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sort_desc(topk(5,aws_s3_bucket_size_bytes_average))",
     "legendFormat": "{{dimension_BucketName}}"
    }
   ]
  }
 ]
}