#!/bin/bash

if [ -z ${KBG_CONTEXT} ]; then
  echo -e "\nERROR: Must set the 'KBG_CONTEXT' env var to the name of the desired cluster to break glass against!\n\n     Example: KBG_CONTEXT=dev-usw2 hack/kbg get nodes\n"
  exit 1
fi

case "${KBG_CONTEXT}" in
    dev-usw2)
        KUBE_CONTEXT="arn:aws:eks:us-west-2:299166832260:cluster/dev-usw2"
    ;;
    build-faster)
        KUBE_CONTEXT="arn:aws:eks:us-east-2:299166832260:cluster/build-faster"
    ;;
    *)
      echo -e "\nERROR: Unknown break glass cluster '${KBG_CONTEXT}'\n"
      exit 1
    ;;
esac

kubectl "$@" --kubeconfig=$HOME/.kube/breakglass --context=${KUBE_CONTEXT}