---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spot-placeholder
  namespace: karpenter
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spot-placeholder
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        karpenter.sh/do-not-disrupt: "true"
      labels:
        app: spot-placeholder
        app.kubernetes.io/name: spot-placeholder
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "eks.amazonaws.com/capacityType"
                    operator: In
                    values:
                      - "SPOT"
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: nativelink
                      operator: In
                      values:
                        - demofs
                topologyKey: topology.kubernetes.io/zone
              weight: 100
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - spot-placeholder
              topologyKey: kubernetes.io/hostname
      containers:
        - image: public.ecr.aws/eks-distro/kubernetes/pause:3.9
          imagePullPolicy: IfNotPresent
          name: inflate
          resources:
            limits:
              memory: 10Mi
            requests:
              cpu: 1m
              memory: 10Mi
      nodeSelector:
        kubernetes.io/arch: amd64
      restartPolicy: Always
      tolerations:
        - key: "nativelink/tolerates-spot"
          operator: Exists