apiVersion: v1
kind: Pod
metadata:
  name: test-isv
  annotations:
    karpenter.sh/do-not-disrupt: "true"
  labels:
    app: test-isv
    app.kubernetes.io/name: test-isv
spec:
  containers:
    - image: public.ecr.aws/eks-distro/kubernetes/pause:3.9
      imagePullPolicy: IfNotPresent
      name: inflate
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
  nodeName: ip-10-0-31-78.us-east-2.compute.internal
  nodeSelector:
    kubernetes.io/arch: amd64
  restartPolicy: Always
  tolerations:
    - key: "nativelink/tolerates-spot"
      operator: Exists