apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "quickwit.fullname" . }}-searcher
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.searcher.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.searcher.replicaCount }}
  serviceName: {{ include "quickwit.fullname" . }}-headless
  {{- if .Values.searcher.podManagementPolicy }}
  podManagementPolicy: {{ .Values.searcher.podManagementPolicy }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "quickwit.searcher.selectorLabels" . | nindent 6 }}
  updateStrategy:
    {{- toYaml .Values.searcher.updateStrategy | nindent 4 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.searcher.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "quickwit.additionalLabels" . | nindent 8 }}
        {{- include "quickwit.searcher.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "quickwit.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - envFrom:
            - configMapRef:
                name: oauth2-proxy-config-logs
            - secretRef:
                name: oauth2-proxy-client
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 8888
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: oauth2-proxy
          ports:
            - containerPort: 8888
              name: proxy
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 8888
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "quickwit.environment" . | nindent 12 }}
            {{- range $key, $value := .Values.searcher.extraEnv }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
          args: ["run", "--service", "searcher"]
          ports:
            {{- include "quickwit.ports" . | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.searcher.startupProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.searcher.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.searcher.readinessProbe | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /quickwit/node.yaml
              subPath: node.yaml
            - name: data
              mountPath: /quickwit/qwdata
            {{- range .Values.configMaps }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
          resources:
            {{- toYaml .Values.searcher.resources | nindent 14 }}
      volumes:
        - name: config
          configMap:
            name: {{ template "quickwit.fullname" . }}
            items:
              - key: node.yaml
                path: node.yaml
        {{- if not .Values.searcher.persistentVolume.enabled }}
        - name: data
          emptyDir: {}
        {{- end }}
        {{- range .Values.configMaps }}
        - name: {{ .name }}
          configMap:
            name: {{ .name }}
        {{- end }}
      {{- with .Values.searcher.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.searcher.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.searcher.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.searcher.persistentVolume.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "{{ .Values.searcher.persistentVolume.storage }}"
      {{- if .Values.searcher.persistentVolume.storageClass }}
        storageClassName: "{{ .Values.searcher.persistentVolume.storageClass }}"
      {{- end }}
  {{- end }}
