{
 "title": "Karpenter Autoscaler",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "nodepool",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable, nodepool)"
    }
   },
   {
    "name": "zone",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable, zone)"
    }
   },
   {
    "name": "arch",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable, arch)"
    }
   },
   {
    "name": "capacity_type",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable, capacity_type)"
    }
   },
   {
    "name": "instance_type",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable, instance_type)"
    }
   },
   {
    "name": "distribution_filter",
    "query": "arch,capacity_type,instance_type,namespace,node,nodepool,zone"
   },
   {
    "name": "controller",
    "label": "Controller",
    "query": {
     "query": "label_values(controller_runtime_reconcile_errors_total, controller)"
    }
   },
   { "name": "trailing", "label": "Trailing", "query": "30s,1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info)" }
   ]
  },
  {
   "title": "CPU Requests to Allocated",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_requests:sum) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Memory Requests to Allocated",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_requests:sum) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "NodePool Summary",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "karpenter_nodepool_usage{resource_type=\"cpu\"} / karpenter_nodepool_limit{resource_type=\"cpu\"}",
     "legendFormat": "CPU Limit Utilization"
    },
    {
     "expr": "count by (nodepool)(karpenter_nodes_allocatable{nodepool!=\"N/A\",resource_type=\"cpu\"}) # Selects a single resource type to get node count"
    },
    {
     "expr": "(karpenter_nodepool_usage{resource_type=\"memory\"} / karpenter_nodepool_limit{resource_type=\"memory\"}) or karpenter_nodepool_limit*0",
     "legendFormat": "Memory Limit Utilization"
    },
    {
     "expr": "sum by (nodepool)(karpenter_nodes_allocatable{nodepool!=\"N/A\",resource_type=\"cpu\"})"
    },
    {
     "expr": "sum by (nodepool)(karpenter_nodes_allocatable{nodepool!=\"N/A\",resource_type=\"memory\"})"
    }
   ]
  },
  {
   "title": "Spot Node Percentage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(count(karpenter_nodes_allocatable{arch=~\"$arch\",capacity_type=\"spot\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"}) or vector(0)) / count(karpenter_nodes_allocatable{arch=~\"$arch\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"})",
     "legendFormat": "Percentage"
    }
   ]
  },
  {
   "title": "Pod Phase",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(phase)(karpenter_pods_state)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "CPU capacity/request/usage",
   "type": "graph",
   "description": "Shows CPU capacity, request, and usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none", "label": "CPU cores" }
   ],
   "targets": [
    { "expr": "sum(machine_cpu_cores)", "legendFormat": "cpu capacity" },
    {
     "expr": "sum by (cluster) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"cpu\"})",
     "legendFormat": "cpu request"
    },
    {
     "expr": "avg(1 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\"}[1m])))) * sum(machine_cpu_cores)",
     "legendFormat": "cpu usage"
    }
   ]
  },
  {
   "title": "Memory capacity/request/usage",
   "type": "graph",
   "description": "Shows Memory capacity, request, and usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "none", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes) / 1000 / 1000 / 1000",
     "legendFormat": "memory capacity"
    },
    {
     "expr": "sum by (cluster) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"memory\"}) / 1000 / 1000 / 1000",
     "legendFormat": "memory request"
    },
    {
     "expr": "avg(1 - (avg_over_time(node_memory_MemFree_bytes[1m]) + avg_over_time(node_memory_Cached_bytes[1m]) + avg_over_time(node_memory_Buffers_bytes[1m])) / avg_over_time(node_memory_MemTotal_bytes[1m])) * sum(node_memory_MemTotal_bytes) / 1000 / 1000 / 1000",
     "legendFormat": "memory usage"
    }
   ]
  },
  {
   "title": "Node Summary",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "((karpenter_nodes_total_daemon_requests{resource_type=\"cpu\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"} or karpenter_nodes_allocatable*0) + \n(karpenter_nodes_total_pod_requests{resource_type=\"cpu\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"} or karpenter_nodes_allocatable*0)) / \nkarpenter_nodes_allocatable{resource_type=\"cpu\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"}",
     "legendFormat": "CPU Utilization"
    },
    {
     "expr": "((karpenter_nodes_total_daemon_requests{resource_type=\"memory\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"} or karpenter_nodes_allocatable*0) + \n(karpenter_nodes_total_pod_requests{resource_type=\"memory\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"} or karpenter_nodes_allocatable*0)) / \nkarpenter_nodes_allocatable{resource_type=\"memory\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"}",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "karpenter_nodes_total_daemon_requests{resource_type=\"pods\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"} + \nkarpenter_nodes_total_pod_requests{resource_type=\"pods\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"}",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "label_replace(\n    sum by (node)(node_time_seconds) - sum by (node)(node_boot_time_seconds),\n    \"node_name\", \"$1\", \"node\", \"(.+)\"\n)",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Pod Distribution: $distribution_filter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum by ($distribution_filter)(\n    karpenter_pods_state{arch=~\"$arch\", capacity_type=~\"$capacity_type\", instance_type=~\"$instance_type\", nodepool=~\"$nodepool\"}\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Startup Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "karpenter_pods_startup_time_seconds{quantile=\"0\"}",
       "legendFormat": "Min"
      },
      {
       "expr": "karpenter_pods_startup_time_seconds{quantile=\"0.5\"}",
       "legendFormat": "P50"
      },
      {
       "expr": "karpenter_pods_startup_time_seconds{quantile=\"0.9\"}",
       "legendFormat": "P90"
      },
      {
       "expr": "karpenter_pods_startup_time_seconds{quantile=\"0.99\"}",
       "legendFormat": "P99"
      },
      {
       "expr": "karpenter_pods_startup_time_seconds{quantile=\"1\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Controller Reconciliation Latency [$controller]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0, rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"$controller\"}[10m]))",
       "legendFormat": "Min"
      },
      {
       "expr": "histogram_quantile(0.5, rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"$controller\"}[10m]))",
       "legendFormat": "P50"
      },
      {
       "expr": "histogram_quantile(0.9, rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"$controller\"}[10m]))",
       "legendFormat": "P90"
      },
      {
       "expr": "histogram_quantile(0.99, rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"$controller\"}[10m]))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(1, rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"$controller\"}[10m]))",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Controller Reconciliation Rate",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(controller_runtime_reconcile_total[10m])) by (controller)",
       "legendFormat": "{{controller}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Items in Work Queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "workqueue_depth{name=\"$controller\"}",
       "legendFormat": "items"
      }
     ]
    },
    {
     "title": "Reconciliations per minute",
     "type": "graph",
     "description": "The rate of completed reconciliations per minute broken out by result status.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(controller_runtime_reconcile_total{controller=\"$controller\"}[$trailing]) * 60",
       "legendFormat": "{{result}}"
      }
     ]
    },
    {
     "title": "Reconciliation duration",
     "type": "heatmap",
     "description": "Aggregates the duration of the reconciliation process.\n\nThe color of each \"bucket\" is a visual clue to the number of reconciliations that completed within that time range.\n\nMouse-over a bucket to display exact values.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
     "targets": [
      {
       "expr": "sum(increase(controller_runtime_reconcile_time_seconds_bucket{controller=\"$controller\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}