{
 "title": "Native Link",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kubecost_cluster_info,id)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", namespace=~\"nativelink-.*\"},namespace)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Kibana Dashboard Links",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "<a title=\"Events & Logs\" target=\"_blank\" href=\"https://log-analytics.${cluster}.nativelink.net/app/dashboards#/view/638fa0a1-bbee-4b80-924a-2465b7315f7b?_g=(filters:!(),refreshInterval:(pause:!t,value:60000),time:(from:'${__from:date:iso}',to:'${__to:date:iso}'))&_a=(query:(language:kuery,query:'log.namespace.keyword:${namespace}%20or%20ing_namespace.keyword:${namespace}%20or%20namespace.keyword:${namespace}'))\">Events &amp; Logs</a>"
   }
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\"}\n) by (workload, workload_type)",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", container!=\"filter\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Ingress Request Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{ingress=~\"$namespace\"}[1m])) by (ingress), 0.001)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Ingress Success Rate (non-4|5xx responses)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{ingress=~\"$namespace\",status!~\"[4-5].*\"}[2m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{ingress=~\"$namespace\"}[2m])) by (ingress)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", pod!~\"builder.*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", pod!~\"builder.*\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "CAS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Action Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nativelink_stores_AC_FAST_SLOW_STORE_fast_store_lower_store_evicting_map_sum_store_size{namespace=\"$namespace\"}",
     "legendFormat": "Store Size (bytes)"
    }
   ]
  },
  {
   "title": "CAS Fast In-Memory Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nativelink_stores_CAS_FAST_SLOW_STORE_inner_store_fast_store_lower_store_evicting_map_sum_store_size{namespace=\"$namespace\"}",
     "legendFormat": "Fast In-Memory Max"
    }
   ]
  },
  {
   "title": "Items in Redis by DB",
   "type": "timeseries",
   "description": "db0 = ActionCache, db1 = CAS, db2 = BEP",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{namespace=~\"$namespace\"}) by (db)",
     "legendFormat": "{{ db }} "
    }
   ]
  },
  {
   "title": "AC / CAS Hit Counts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nativelink_stores_AC_FAST_SLOW_STORE_fast_store_hit_count{namespace=\"$namespace\"}",
     "legendFormat": "AC Fast Store Hits"
    },
    {
     "expr": "nativelink_stores_AC_FAST_SLOW_STORE_slow_store_hit_count{namespace=\"$namespace\"}",
     "legendFormat": "AC Slow Store Hits"
    },
    {
     "expr": "nativelink_stores_CAS_FAST_SLOW_STORE_inner_store_fast_store_hit_count{namespace=\"$namespace\"}",
     "legendFormat": "CAS Fast Store Hits"
    },
    {
     "expr": "nativelink_stores_CAS_FAST_SLOW_STORE_inner_store_slow_store_hit_count{namespace=\"$namespace\"}",
     "legendFormat": "CAS Slow Store Hits"
    }
   ]
  },
  { "title": "Remote Execution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Queued Tasks per Container Image",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (container_image) (scale_up_queued_tasks_per_image{namespace=~\"$namespace\"})",
     "legendFormat": "{{container_image}}"
    }
   ]
  },
  {
   "title": "Queued Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "targets": [
    {
     "expr": "scale_up_queued_tasks{namespace=\"$namespace\"}",
     "legendFormat": "Task Count"
    }
   ]
  },
  {
   "title": "Tasks (1-min rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (namespace) (irate(nativelink_workers_worker_0_execute_successes{namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "Execute Successes"
    },
    {
     "expr": "sum by (namespace) (irate(nativelink_workers_worker_0_task_timeouts_counter{namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "Timeouts"
    },
    {
     "expr": "sum by (namespace) (irate(nativelink_workers_worker_0_execute_failures{namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "Execute Failures"
    }
   ]
  },
  {
   "title": "Scheduler Actions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum by (namespace) (increase(nativelink_action_schedulers_MAIN_SCHEDULER_worker_run_action_successes{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Successes"
    },
    {
     "expr": "sum by (namespace) (increase(nativelink_action_schedulers_MAIN_SCHEDULER_worker_run_action_failures{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "Worker Pods",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 8, "y": 53 },
   "targets": [
    {
     "expr": "sum by(phase)(karpenter_pods_state{exported_namespace=\"$namespace\",name=~\"worker.*\",name!~\"worker-provisioner.*\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Scale-up Rate (per Hash)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 53 },
   "targets": [
    {
     "expr": "sum by(worker_hash)(rate(scale_up_pods_added_per_hash_count{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Worker CPU Usage / Requests / Limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=\"worker\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"worker\", resource=\"cpu\"}\n)\n",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"worker\", resource=\"cpu\"}\n)\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Worker Memory Usage / Requests / Limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", container=\"worker\", image!=\"\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"worker\", resource=\"memory\"}\n)\n",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", container=\"worker\", resource=\"memory\"}\n)\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Worker Nodes",
   "type": "piechart",
   "description": "Link to Node Exporter full dashboard for nodes that are hosting workers in this claim.",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (node) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\"worker.*\", pod!~\"worker-provisioner.*\"}) * on (node) group_left(instance) label_replace(node_uname_info, \"node\", \"$1\", \"nodename\", \"(.*)\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Infrastructure Events",
   "type": "logs",
   "description": "Abnormal infrastructure events related to your deployment in NativeLink cloud.",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 71 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "namespace.keyword: \"$namespace\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}